### ISSUE TITLE
[feature request] Audio feedback on wake-word detection

### ISSUE THREAD

**Issue by u17194907425** [thanksmister/voice-panel-android#11]
Requesting to **add a configurable audio feedback when a wake-word is detected** by the assistant. It can be like a beep or a "yes" over TTS.

**Reasoning**: Currently there is video feedback on wake-word detection. The icon is being animated. It is not working in case the device is used while not looking at the screen. E.g. the device running Voice Panel might be installed hidden so that it is just a "smart microphone".

Thank you!

**Comment by u17194907425** [comment]
Confirm as working on https://github.com/thanksmister/voice-panel-android/releases/tag/v0.1.4.0
Thank you!

**Comment by thanksmister** [comment]
Awsome! Let me know if you see any issues.
