### ISSUE TITLE
[feature request] make 'siteId' intent option configurable

### ISSUE THREAD

**Issue by u17194907425** [thanksmister/voice-panel-android#12]
**Request**
Please make `siteId` parameter of the `hermes/intent/` configurable via the Voice Assistant settings.

**Motivation**
This customization feature is required in order to distinguish intents in case there are more then one device running Voice Panel in the house. Ability to configure `siteId` will enable context-specific commands.

**Examples**
Based on `siteId` there might be different reaction on such a command like "_hey Snips, turn on the lights_".

**Currently observed behavior**
* I see the following in any intent received by HASS: `"siteId":"default"`
* Sample:
`{'topic': 'hermes/intent/hass:HassTurnOn', 'payload': '{"customData":null,"input":"turn on the flower","intent":{"confidenceScore":0.9853135,"intentName":"hass:HassTurnOn"},"sessionId":"a7326574-32c6-483e-9a68-9f392a6abadc","siteId":"default","slots":[{"confidenceScore":1.0,"entity":"hass_entity","range":{"end":18,"start":12},"rawValue":"flower","slotName":"name","value":{"value":"flower","kind":"CUSTOM"}}]}'}
`

**References**
https://docs.snips.ai/reference/dialogue#intent
`siteId`: String - Site where the user interaction took place.

**Comment by thanksmister** [comment]
I can modify the outgoing JSON and manually set the `siteId` value before sending it to HA.  There doesn't seem to be a way to initially set this in the Android Snips SDK.   I am thinking to use the Mqtt base topic value which is used for the Mqtt broker to identify individual clients from each other in the same network.   

The other option would be to use the `clientId`, which is randomly generated, but you can also customized in the MQTT setup.    However, I am leaning towards using the base topic as its more human readable when first created.  So instead of using the default `voicepanel`, you could use `voicepanel_living` to make each device unique and send MQTT commands to this particular client.  

I think this would give you what you need to distinguish one device from another.

**Comment by u17194907425** [comment]
I like the idea of the topic. However, just to double-check - if we are talking about the intent, then unless I miss something the topic is pretty much strictly defined in the API as `hermes/intent/<intentName>`.

For me personally it will be fine if the topic is different. I have my own MQTT handler inside an AppDaemon so I can subscribe to anything on HA side... I just wonder if this change of the topic could break the existing functionality for other users when instead of `hermes/intent/<intentName>` there will be something else.

Or I did get your idea completely wrong? :)

**Comment by thanksmister** [comment]
I am talking about the MQTT base topic, which is used when sending MQTT commands back to individual devices, so if you send a TTS command to the MQTT client, the base topic differentiates one client from another.   

This will not change the `hermes/intent/<intentName>`, we are just using the current MQTT base topic in the settings of the app as the `clientId`.  Check the Command section in the documentation: https://github.com/thanksmister/voice-panel-android#commands

This should not interfere with anything currently setup, it will only provide you with a customizable and unique `siteId` value that you can use to differentiate each client when receiving the JSON intent from the snips client.   Does that make sense?

**Comment by thanksmister** [comment]
Specifically from the documentation:

> The base topic value (default is "voicepanel") should be unique to each device running the application unless you want all devices to receive the same command. The base topic and can be changed in the application settings.

**Comment by thanksmister** [comment]
If it's less confusing, we can use the applications `clientId` value which is unique to every instance of the application.   This won't confuse things with the base topic and MQTT, though the `clientId` is also used to to connect to the MQTT broker (HA) and you can see this value in the MQTT logs.

**Comment by u17194907425** [comment]
Ah... I think I just got confused with the message of not being able to set this `clientId` via SDK.
It looks like I should read it likethis:

_I am thinking to use the Mqtt base topic **as the `clientId`** value which is used for the Mqtt broker to identify individual clients from each other in the same network._

So the intent will looks something like this, right?
`
{'topic': 'hermes/intent/hass:HassTurnOn', 'payload': '{"customData":null,"input":"turn on the flower","intent":{"confidenceScore":0.9853135,"intentName":"hass:HassTurnOn"},"sessionId":"a7326574-32c6-483e-9a68-9f392a6abadc","siteId":"` **voicepanel_living** `","slots":[{"confidenceScore":1.0,"entity":"hass_entity","range":{"end":18,"start":12},"rawValue":"flower","slotName":"name","value":{"value":"flower","kind":"CUSTOM"}}]}'}`

**Comment by thanksmister** [comment]
Yes, that is what it would like like.  If we use the applications Client Id value, which is in the MQTT settings of the app at the bottom, for the `siteId` value it would be like this:

```{'topic': 'hermes/intent/hass:HassTurnOn', 'payload': '{"customData":null,"input":"turn on the flower","intent":{"confidenceScore":0.9853135,"intentName":"hass:HassTurnOn"},"sessionId":"a7326574-32c6-483e-9a68-9f392a6abadc","siteId":"14c8b12292a4cb129a8174dc10b118c610cae13a", "slots":[{"confidenceScore":1.0,"entity":"hass_entity","range":{"end":18,"start":12},"rawValue":"flower","slotName":"name","value":{"value":"flower","kind":"CUSTOM"}}]}'}```

You can of course customize the Client Id value in the settings.  The reason I suggested base topic is because this is also used to distinguish between topics and its default value is readable in the settings as `voicepanel` rather than `14c8b12292a4cb129a8174dc10b118c610cae13a`.   

However, it may not be initially obvious that the base topic would also be used as a site id.  I am just trying to reuse information we already have rather than create a new value just for `siteId`, but it may just be more user friendly to create a separate `siteId` value in the assistant settings.

**Comment by thanksmister** [comment]
I also check the `sessionId` value on the returned response so that it matches the application that sent the intent to the Snips server.  This may already be filtering out responses so that only specific devices will be able to use them.    If decided to use the base topic for the `siteId` because this give us the advantage of sending a custom MQTT command back to the specific device (like a TTS response).  

So the default intent will look like like the following until the user changes the base topic for the device:

```{'topic': 'hermes/intent/hass:HassTurnOn', 'payload': '{"customData":null,"input":"turn on the flower","intent":{"confidenceScore":0.9853135, "intentName":"hass:HassTurnOn"}, "sessionId":"a7326574-32c6-483e-9a68-9f392a6abadc", "siteId":"voicepanel", "slots":[{"confidenceScore":1.0, "entity":"hass_entity", "range":{"end":18,"start":12}, "rawValue":"flower", "slotName":"name", "value":{"value":"flower","kind":"CUSTOM"}}]}'}```

**Comment by u17194907425** [comment]
Thank you!
I was just testing the beta build https://github.com/thanksmister/voice-panel-android/releases/tag/v0.1.4.0 and still the "siteId" is "default".

What I did:

- uninstall app installed from Google Store
- install beta
- configure MQTT
- set Base topic to "voicepanel_mimax"
- speak a command
- the output is this:

`core-ssh:~# mosquitto_sub -h 192.168.0.18 -p 1883 -u mqtt -P mqtt -v -t 'hermes/#'
hermes/intent/hass:HassTurnOn {"customData":null,"input":"turn on the lights","intent":{"confidenceScore":0.9878511,"intentName":"hass:HassTurnOn"},"sessionId":"821628ae-380b-4e8c-849d-0d82b5ad70fe","siteId":"default","slots":[{"confidenceScore":1.0,"entity":"hass_entity","range":{"end":18,"start":12},"rawValue":"lights","slotName":"name","value":{"value":"Lights","kind":"CUSTOM"}}]}`

Am I doing something wrong?

**Comment by thanksmister** [comment]
I see I have it set properly, but remapped the unmodified version of the object to send it as JSON.  Let me issue an update real quick to address it.

**Comment by thanksmister** [comment]
Here is the correct output for the json and command:

command: `hermes/intent/rgholmes:getCurrentTime`

message:``` {"createdAt":"2019-06-05T14:39:13-0300","customData":null,"input":"what time is it","intent":{"intentName":"rgholmes:getCurrentTime","probability":null},"response":{"sessionId":null,"text":null},"sessionId":"24551294-79eb-4838-a634-4af65e9c86ee","siteId":"voicepanel","slots":[],"uid":0}```

I am hoping that the response voice I added, saying "Yes" doesn't delay the listening time, I am testing that change further to be sure I don't see inconsistencies.   You can't actually stop Snips from listening after it hears the wake word, so its expecting a command when its saying "Yes".

**Comment by u17194907425** [comment]
Confirmed on v0.1.4-beta.1. "siteId":"voicepanel_mimax"
`hermes/intent/hass:HassTurnOff {"createdAt":"2019-06-05T23:36:57+0300","customData":null,"input":"turn off the flower","intent":{"intentName":"hass:HassTurnOff","probability":null},"response":{"sessionId":null,"text":null},"sessionId":"b46d30d4-646e-4564-8f98-d650cedde842","siteId":"voicepanel_mimax","slots":[{"entity":"hass_entity","range":{"end":19,"start":13},"rawValue":"flower","slotName":"name","value":{"kind":"CUSTOM","value":"flower"}}],"uid":0}`

Along with that I see a change in the payload structure in general:

- "createdAt" property has arrived
- no "confidenceScore" property neither inside "intent" nor inside "slot"
- "probability" property has arrived for "intent"
- "response" property has arrived

I can understand from the `VoicePanelService.kt` how "createdAt" and "response" have started to appear with the latest change. What I don't understand, how the "confidenceScore" has gone away :/

**Comment by thanksmister** [comment]
Well, nothing was removed from the object, only added.  I have to investigate to see if its just something with Snips intents, maybe they don't always post it.

**Comment by thanksmister** [comment]
This is because the json doesn't match the object mapping, I am going to revert out that change for now until I can better map the json output without losing the parameters.    This happened due to a change in the Snips API and renaming the parameters.

**Comment by thanksmister** [comment]
This is the raw json from the Snips Android SDK:

```{"customData":null,"input":"what time is it","intent":{"confidenceScore":1.0,"intentName":"rgholmes:getCurrentTime"},"sessionId":"65a29b61-fc78-4d5a-be7e-b16eb685b3f2","siteId":"default","slots":[]}```

**Comment by thanksmister** [comment]
I had to do a quick hack for now, but swapped out the string in the json for what we want so I don't pollute the json intent.

```{"customData":null,"input":"what time is it","intent":{"confidenceScore":1.0,"intentName":"rgholmes:getCurrentTime"},"sessionId":"f9d5a6e7-4c5d-4a1c-9ca6-860a89d719db","siteId":"voicepanel","slots":[]}``` . 

This removes the extra params as well.
