### ISSUE TITLE
High battery usage

### ISSUE THREAD

**Issue by CazMan** [thanksmister/voice-panel-android#16]
I am testing this app on a Samsung galaxy s8 and noticed that the app uses a lot of battery - the phone heats up andit is warm to the touch - even the fast charger cant seem to keep up with the power usage.

I had it open for 4 minutes and the Battery usage of the app is is 2.2%? 
No other features are configured (camera streaming and sensors are all off)

Is snips really using so much power just to listen to the wake word?

**Comment by thanksmister** [comment]
The short answer is yes, Snips does draw a lot of juice.  However it’s also about the device and the version of OS.  Some apps on some devices draw a lot more power than others and there isn’t much that can be done.  

Google devices seem to be the best and in my experience Samsung devices seem to run very hot.   

Perhaps you have screensaver feature or other energy feature you could use?   I know there is Daydream for Android but it’s not available in all devices.
