### ISSUE TITLE
SnipsAPI change (probability -> confidenceScore)

### ISSUE THREAD

**Issue by Dobli** [thanksmister/voice-panel-android#6]
The recent Snips SDK update now uses the term 'confidenceScore' instead of  'probability'. Home Assistant Adapted to this and the Snips Component now expects a 'confidenceScore'. Therefore Voice Panel does not work anymore with recent HA Versions.

Maybe it is enough to simply update the Snips SDK to make it work again.

**Comment by thanksmister** [comment]
Thanks, I take a look no see but the application doesn’t send either of these values to HA.  

The Snips SDK for Android works on the device and the confidence or probability scores are run on the device without any connection to the Snips service.  

However there may be other breaking changes in the API used to communicate with HA.

So it should not matter if HA is using a confidence score as the Android a probability score since it’s not shared.

**Comment by Dobli** [comment]
Hmm when I try a Voice Command I get the following error in my HA Log:
```
Exception in message_received when handling msg on 'hermes/intent/hass:HassTurnOff': '{"customData":null,"input":"turn off the lights","intent":{"intentName":"hass:HassTurnOff","probability":0.99261343},"sessionId":"1111111-111111-1111-11111111111","siteId":"default","slots":[{"confidence":-1.0,"entity":"hass_entity","range":{"end":19,"start":13},"rawValue":"lights","slotName":"name","value":{"value":"Lights","kind":"CUSTOM"}}]}'
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/components/snips/__init__.py", line 108, in message_received
    if (request['intent']['confidenceScore']
KeyError: 'confidenceScore'
```

It seems to be caused by a MQTT message pushed to `hermes/intent/hass:HassTurnOff` and it contains the voice command I used.

**Comment by thanksmister** [comment]
I am currently testing the issue now and will let you know what I find.

**Comment by thanksmister** [comment]
The Voice Panel application still works with Home Assistant v0.87.0.  Which version of HA are you using, I am trying to determine when this change was made for the Snips component in HA.  If I release an updated version of the application with a new Snips SDK and I am on an older version of HA, the application will probably not work either.    So I need to make sure to put that in the release notes that a certain version of HA is required.

**Comment by Dobli** [comment]
I use the latest version (0.90). I've just checked it, the change in HA was part of release 0.89.0. (see the [changelog](https://github.com/home-assistant/home-assistant/releases/tag/0.89.0) and this [pull request](https://github.com/home-assistant/home-assistant/pull/21443)).
Thanks for taking time to look into it.

**Comment by thanksmister** [comment]
Ok, I have to update my HA version first and then test the new Snips SDK version.  If all goes well, I will roll out a new version soon with notes directing users to update to v0.90 of HA minimum.

**Comment by thanksmister** [comment]
In testing the new SDK, it breaks the application.  I am awaiting a response from Snips about the issue.

**Comment by thanksmister** [comment]
I was able to get the new SDK running and verified the confidenceScore change in the JSON output sent  out by Snips:

```IntentMessage {
            session_id: "c68d4496-c32e-4280-97f9-c53cc734c9eb",
            custom_data: None,
            site_id: "default",
            input: "what time is it",
            asr_tokens: Some(
                [
                    [
                        AsrToken {
                            value: "what",
                            confidence: 1.0,
                            range_start: 0,
                            range_end: 4,
                            time: AsrDecodingDuration {
                                start: 0.0,
                                end: 1.0799999
                            }
                        },
                        AsrToken {
                            value: "time",
                            confidence: 1.0,
                            range_start: 5,
                            range_end: 9,
                            time: AsrDecodingDuration {
                                start: 1.0799999,
                                end: 1.14
                            }
                        },
                        AsrToken {
                            value: "is",
                            confidence: 0.94273466,
                            range_start: 10,
                            range_end: 12,
                            time: AsrDecodingDuration {
                                start: 1.14,
                                end: 1.3412218
                            }
                        },
                        AsrToken {
                            value: "it",
                            confidence: 0.9607765,
                            range_start: 13,
                            range_end: 15,
                            time: AsrDecodingDuration {
                                start: 1.3412218,
                                end: 2.2641084
                            }
                        }
                    ]
                ]
            ),
            intent: NluIntentClassifierResult {
                intent_name: "rgholmes:getCurrentTime",
                confidence_score: 1.0
            },
            slots: []
        }
    }```

**Comment by thanksmister** [comment]
Issuing a new application in a few moments, will close this issue for now.

**Comment by Dobli** [comment]
Wow thanks, that was quick, I will try it later. :)
