### ISSUE TITLE
Non-english language support

### ISSUE THREAD

**Issue by Matte23** [thanksmister/voice-panel-android#7]
It would be nice to support non english languages with snips. Maybe it can be implemented by offering the option of using a custom "assistant.zip" file, as alterative to the default one.

**Comment by thanksmister** [comment]
This is why the application is open source.  You can compile the application with your own assistant.

**Comment by Matte23** [comment]
You're right, thanks 👍 . Are pull request welcome? Maybe I can write a small patch for users which don't know programming

**Comment by thanksmister** [comment]
You will also have to add your own language to the some of the Snips apps used, or those that you want to use for your assistant.   You do that from the snips console and fork the app.  I think in the documentation I listed all the apps I used for the assistant, a few I created myself just for this app.   It's going to be some work, hence why its not easy to freely add multiple language support.  https://console.snips.ai/

**Comment by Matte23** [comment]
Got it, thanks
